IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE  OBJECT_ID = OBJECT_ID(N'Product'))
BEGIN
CREATE TABLE [dbo].[Product](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[ProductCode] [varchar](25) NOT NULL,
	[ProductName] [varchar](25) NOT NULL,
	[ProductQuantity] [int] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Product' AND COLUMN_NAME = 'Active' AND TABLE_SCHEMA = 'DBO' AND COLUMN_DEFAULT IS NULL)
BEGIN
ALTER TABLE [Product] ADD  DEFAULT (1) FOR [Active]
END
GO

IF NOT EXISTS(SELECT 1 FROM SYS.TABLES WHERE  OBJECT_ID = OBJECT_ID(N'OrderProduct'))
BEGIN
CREATE TABLE [dbo].[OrderProduct](
	[OrderId] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[ProductQuantity] [int] NOT NULL,
	[Active] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO


IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OrderProduct' AND COLUMN_NAME = 'Active' AND TABLE_SCHEMA = 'DBO' AND COLUMN_DEFAULT IS NULL)
BEGIN
ALTER TABLE [OrderProduct] ADD  DEFAULT (1) FOR [Active]
END
GO